[modules]
  [modules.preprocessor]
    name = "verification.db.transfer.TransferPreparer"
    path = "verification-db/build/libs/verification-db-all.jar"
  [modules.processor]
    name = "verification.db.transfer.TransferProcessor"
    path = "verification-db/build/libs/verification-db-all.jar"
  [modules.postprocessor]
    name = "verification.db.transfer.TransferChecker"
    path = "verification-db/build/libs/verification-db-all.jar"
  [[modules.injectors]]
    name = "verification.db.transfer.CassandraKiller"
    path = "verification-db/build/libs/verification-db-all.jar"

[common]
  concurrency = 5
  run_for_sec = 20
  ramp_for_sec = 10

[test_config]
  contact_points = "localhost"
  num_accounts = 10
  population_concurrency = 8

[killer_config]
  ssh_user = "centos"
  ssh_port = 22
  ssh_private_key = "/home/centos/.ssh/private_key"
  contact_points = "localhost"
  max_kill_interval_sec = 300
