[modules]
  [modules.preprocessor]
    name = "org.my.Preparer"
    path = "/path/to/preparer"
  [modules.processor]
    name = "org.my.Processor"
    path = "/path/to/processor"
  [modules.postprocessor]
    name = "org.my.Checker"
    path = "/path/to/checker"
  [modules.injector]
    name = "org.my.Injector"
    path = "/path/to/injector"

[common]
  concurrency = 4
  run_for_sec = 100
  ramp_for_sec = 10

[my_test_config]
  accounts = 10000
  balance = 1000
