[modules]
  [modules.preprocessor]
    name = "benchmark.client.transfer.TransferPreparer"
    path = "benchmark-client/build/libs/benchmark-client-all.jar"
  [modules.processor]
    name = "benchmark.client.transfer.TransferProcessor"
    path = "benchmark-client/build/libs/benchmark-client-all.jar"
  [modules.postprocessor]
    name = "benchmark.client.transfer.TransferReporter"
    path = "benchmark-client/build/libs/benchmark-client-all.jar"

[common]
  concurrency = 1
  run_for_sec = 200
  ramp_for_sec = 10

[performance_monitor]
  enabled = true
  progress_throughput_enabled = true

[test_config]
  num_accounts = 100000
  population_concurrency = 32
  population_contract_name = "benchmark.contract.BatchCreate"
  population_contract_path = "benchmark-client/build/classes/java/main/benchmark/contract/BatchCreate.class"
  transfer_contract_name = "benchmark.contract.Transfer"
  transfer_contract_path = "benchmark-client/build/classes/java/main/benchmark/contract/Transfer.class"

[client_config]
  dl_server = "localhost"
  # dl_server_port = 50051
  certificate = "benchmark-client/sample-keys/certificate.pem"
  private_key = "benchmark-client/sample-keys/private-key.pem"
