name: Kelpie

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v4

    - name: Cache repository
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build Kelpie
      run: ./gradlew build

    - name: Install distribution of Kelpie
      run: ./gradlew installDist

    - name: Checkout Kelpie-Test
      uses: actions/checkout@v4
      with:
        repository: scalar-labs/kelpie-test
        path: kelpie-test

    - name: Build Kelpie-Test:print-modules
      working-directory: kelpie-test/print-modules
      run: ${{ github.workspace }}/gradlew shadowJar

    - name: Execute Kelpie-Test:print-modules
      working-directory: kelpie-test
      run: ${{ github.workspace }}/build/install/kelpie/bin/kelpie --config print-modules/config.toml
