name: Kelpie

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v2

    - name: Cache repository
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build Kelpie and modules
      run: ./gradlew build

    - name: Test a sample
      run: |
        ./gradlew installDist
        ./kelpie/build/install/kelpie/bin/kelpie --config print-modules/print.toml --inject
